// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/protoReqRecv.proto

package server;

public final class ProtoReqRecv {
  private ProtoReqRecv() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server.Order)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string company = 1;</code>
     */
    java.lang.String getCompany();
    /**
     * <code>string company = 1;</code>
     */
    com.google.protobuf.ByteString
        getCompanyBytes();

    /**
     * <code>int32 quantity = 2;</code>
     */
    int getQuantity();

    /**
     * <code>int32 price_min_max = 3;</code>
     */
    int getPriceMinMax();
  }
  /**
   * Protobuf type {@code server.Order}
   */
  public  static final class Order extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:server.Order)
      OrderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Order.newBuilder() to construct.
    private Order(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Order() {
      company_ = "";
      quantity_ = 0;
      priceMinMax_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Order(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              company_ = s;
              break;
            }
            case 16: {

              quantity_ = input.readInt32();
              break;
            }
            case 24: {

              priceMinMax_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return server.ProtoReqRecv.internal_static_server_Order_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return server.ProtoReqRecv.internal_static_server_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              server.ProtoReqRecv.Order.class, server.ProtoReqRecv.Order.Builder.class);
    }

    public static final int COMPANY_FIELD_NUMBER = 1;
    private volatile java.lang.Object company_;
    /**
     * <code>string company = 1;</code>
     */
    public java.lang.String getCompany() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        company_ = s;
        return s;
      }
    }
    /**
     * <code>string company = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyBytes() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        company_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 2;
    private int quantity_;
    /**
     * <code>int32 quantity = 2;</code>
     */
    public int getQuantity() {
      return quantity_;
    }

    public static final int PRICE_MIN_MAX_FIELD_NUMBER = 3;
    private int priceMinMax_;
    /**
     * <code>int32 price_min_max = 3;</code>
     */
    public int getPriceMinMax() {
      return priceMinMax_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCompanyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, company_);
      }
      if (quantity_ != 0) {
        output.writeInt32(2, quantity_);
      }
      if (priceMinMax_ != 0) {
        output.writeInt32(3, priceMinMax_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCompanyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, company_);
      }
      if (quantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, quantity_);
      }
      if (priceMinMax_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, priceMinMax_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof server.ProtoReqRecv.Order)) {
        return super.equals(obj);
      }
      server.ProtoReqRecv.Order other = (server.ProtoReqRecv.Order) obj;

      boolean result = true;
      result = result && getCompany()
          .equals(other.getCompany());
      result = result && (getQuantity()
          == other.getQuantity());
      result = result && (getPriceMinMax()
          == other.getPriceMinMax());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMPANY_FIELD_NUMBER;
      hash = (53 * hash) + getCompany().hashCode();
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
      hash = (37 * hash) + PRICE_MIN_MAX_FIELD_NUMBER;
      hash = (53 * hash) + getPriceMinMax();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static server.ProtoReqRecv.Order parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.ProtoReqRecv.Order parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.ProtoReqRecv.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.ProtoReqRecv.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.ProtoReqRecv.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.ProtoReqRecv.Order parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.ProtoReqRecv.Order parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static server.ProtoReqRecv.Order parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static server.ProtoReqRecv.Order parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static server.ProtoReqRecv.Order parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static server.ProtoReqRecv.Order parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static server.ProtoReqRecv.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(server.ProtoReqRecv.Order prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server.Order}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server.Order)
        server.ProtoReqRecv.OrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return server.ProtoReqRecv.internal_static_server_Order_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return server.ProtoReqRecv.internal_static_server_Order_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                server.ProtoReqRecv.Order.class, server.ProtoReqRecv.Order.Builder.class);
      }

      // Construct using server.ProtoReqRecv.Order.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        company_ = "";

        quantity_ = 0;

        priceMinMax_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return server.ProtoReqRecv.internal_static_server_Order_descriptor;
      }

      public server.ProtoReqRecv.Order getDefaultInstanceForType() {
        return server.ProtoReqRecv.Order.getDefaultInstance();
      }

      public server.ProtoReqRecv.Order build() {
        server.ProtoReqRecv.Order result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public server.ProtoReqRecv.Order buildPartial() {
        server.ProtoReqRecv.Order result = new server.ProtoReqRecv.Order(this);
        result.company_ = company_;
        result.quantity_ = quantity_;
        result.priceMinMax_ = priceMinMax_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof server.ProtoReqRecv.Order) {
          return mergeFrom((server.ProtoReqRecv.Order)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(server.ProtoReqRecv.Order other) {
        if (other == server.ProtoReqRecv.Order.getDefaultInstance()) return this;
        if (!other.getCompany().isEmpty()) {
          company_ = other.company_;
          onChanged();
        }
        if (other.getQuantity() != 0) {
          setQuantity(other.getQuantity());
        }
        if (other.getPriceMinMax() != 0) {
          setPriceMinMax(other.getPriceMinMax());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        server.ProtoReqRecv.Order parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (server.ProtoReqRecv.Order) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object company_ = "";
      /**
       * <code>string company = 1;</code>
       */
      public java.lang.String getCompany() {
        java.lang.Object ref = company_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          company_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string company = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCompanyBytes() {
        java.lang.Object ref = company_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          company_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string company = 1;</code>
       */
      public Builder setCompany(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        company_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string company = 1;</code>
       */
      public Builder clearCompany() {
        
        company_ = getDefaultInstance().getCompany();
        onChanged();
        return this;
      }
      /**
       * <code>string company = 1;</code>
       */
      public Builder setCompanyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        company_ = value;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>int32 quantity = 2;</code>
       */
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>int32 quantity = 2;</code>
       */
      public Builder setQuantity(int value) {
        
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quantity = 2;</code>
       */
      public Builder clearQuantity() {
        
        quantity_ = 0;
        onChanged();
        return this;
      }

      private int priceMinMax_ ;
      /**
       * <code>int32 price_min_max = 3;</code>
       */
      public int getPriceMinMax() {
        return priceMinMax_;
      }
      /**
       * <code>int32 price_min_max = 3;</code>
       */
      public Builder setPriceMinMax(int value) {
        
        priceMinMax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 price_min_max = 3;</code>
       */
      public Builder clearPriceMinMax() {
        
        priceMinMax_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:server.Order)
    }

    // @@protoc_insertion_point(class_scope:server.Order)
    private static final server.ProtoReqRecv.Order DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new server.ProtoReqRecv.Order();
    }

    public static server.ProtoReqRecv.Order getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Order>
        PARSER = new com.google.protobuf.AbstractParser<Order>() {
      public Order parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Order(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Order> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Order> getParserForType() {
      return PARSER;
    }

    public server.ProtoReqRecv.Order getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GeneralOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server.General)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.server.Order order = 1;</code>
     */
    boolean hasOrder();
    /**
     * <code>.server.Order order = 1;</code>
     */
    server.ProtoReqRecv.Order getOrder();
    /**
     * <code>.server.Order order = 1;</code>
     */
    server.ProtoReqRecv.OrderOrBuilder getOrderOrBuilder();

    public server.ProtoReqRecv.General.GeneralCase getGeneralCase();
  }
  /**
   * Protobuf type {@code server.General}
   */
  public  static final class General extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:server.General)
      GeneralOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use General.newBuilder() to construct.
    private General(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private General() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private General(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              server.ProtoReqRecv.Order.Builder subBuilder = null;
              if (generalCase_ == 1) {
                subBuilder = ((server.ProtoReqRecv.Order) general_).toBuilder();
              }
              general_ =
                  input.readMessage(server.ProtoReqRecv.Order.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((server.ProtoReqRecv.Order) general_);
                general_ = subBuilder.buildPartial();
              }
              generalCase_ = 1;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return server.ProtoReqRecv.internal_static_server_General_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return server.ProtoReqRecv.internal_static_server_General_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              server.ProtoReqRecv.General.class, server.ProtoReqRecv.General.Builder.class);
    }

    private int generalCase_ = 0;
    private java.lang.Object general_;
    public enum GeneralCase
        implements com.google.protobuf.Internal.EnumLite {
      ORDER(1),
      GENERAL_NOT_SET(0);
      private final int value;
      private GeneralCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static GeneralCase valueOf(int value) {
        return forNumber(value);
      }

      public static GeneralCase forNumber(int value) {
        switch (value) {
          case 1: return ORDER;
          case 0: return GENERAL_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public GeneralCase
    getGeneralCase() {
      return GeneralCase.forNumber(
          generalCase_);
    }

    public static final int ORDER_FIELD_NUMBER = 1;
    /**
     * <code>.server.Order order = 1;</code>
     */
    public boolean hasOrder() {
      return generalCase_ == 1;
    }
    /**
     * <code>.server.Order order = 1;</code>
     */
    public server.ProtoReqRecv.Order getOrder() {
      if (generalCase_ == 1) {
         return (server.ProtoReqRecv.Order) general_;
      }
      return server.ProtoReqRecv.Order.getDefaultInstance();
    }
    /**
     * <code>.server.Order order = 1;</code>
     */
    public server.ProtoReqRecv.OrderOrBuilder getOrderOrBuilder() {
      if (generalCase_ == 1) {
         return (server.ProtoReqRecv.Order) general_;
      }
      return server.ProtoReqRecv.Order.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (generalCase_ == 1) {
        output.writeMessage(1, (server.ProtoReqRecv.Order) general_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (generalCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (server.ProtoReqRecv.Order) general_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof server.ProtoReqRecv.General)) {
        return super.equals(obj);
      }
      server.ProtoReqRecv.General other = (server.ProtoReqRecv.General) obj;

      boolean result = true;
      result = result && getGeneralCase().equals(
          other.getGeneralCase());
      if (!result) return false;
      switch (generalCase_) {
        case 1:
          result = result && getOrder()
              .equals(other.getOrder());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (generalCase_) {
        case 1:
          hash = (37 * hash) + ORDER_FIELD_NUMBER;
          hash = (53 * hash) + getOrder().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static server.ProtoReqRecv.General parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.ProtoReqRecv.General parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.ProtoReqRecv.General parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.ProtoReqRecv.General parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.ProtoReqRecv.General parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static server.ProtoReqRecv.General parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static server.ProtoReqRecv.General parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static server.ProtoReqRecv.General parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static server.ProtoReqRecv.General parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static server.ProtoReqRecv.General parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static server.ProtoReqRecv.General parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static server.ProtoReqRecv.General parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(server.ProtoReqRecv.General prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server.General}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server.General)
        server.ProtoReqRecv.GeneralOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return server.ProtoReqRecv.internal_static_server_General_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return server.ProtoReqRecv.internal_static_server_General_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                server.ProtoReqRecv.General.class, server.ProtoReqRecv.General.Builder.class);
      }

      // Construct using server.ProtoReqRecv.General.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        generalCase_ = 0;
        general_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return server.ProtoReqRecv.internal_static_server_General_descriptor;
      }

      public server.ProtoReqRecv.General getDefaultInstanceForType() {
        return server.ProtoReqRecv.General.getDefaultInstance();
      }

      public server.ProtoReqRecv.General build() {
        server.ProtoReqRecv.General result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public server.ProtoReqRecv.General buildPartial() {
        server.ProtoReqRecv.General result = new server.ProtoReqRecv.General(this);
        if (generalCase_ == 1) {
          if (orderBuilder_ == null) {
            result.general_ = general_;
          } else {
            result.general_ = orderBuilder_.build();
          }
        }
        result.generalCase_ = generalCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof server.ProtoReqRecv.General) {
          return mergeFrom((server.ProtoReqRecv.General)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(server.ProtoReqRecv.General other) {
        if (other == server.ProtoReqRecv.General.getDefaultInstance()) return this;
        switch (other.getGeneralCase()) {
          case ORDER: {
            mergeOrder(other.getOrder());
            break;
          }
          case GENERAL_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        server.ProtoReqRecv.General parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (server.ProtoReqRecv.General) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int generalCase_ = 0;
      private java.lang.Object general_;
      public GeneralCase
          getGeneralCase() {
        return GeneralCase.forNumber(
            generalCase_);
      }

      public Builder clearGeneral() {
        generalCase_ = 0;
        general_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          server.ProtoReqRecv.Order, server.ProtoReqRecv.Order.Builder, server.ProtoReqRecv.OrderOrBuilder> orderBuilder_;
      /**
       * <code>.server.Order order = 1;</code>
       */
      public boolean hasOrder() {
        return generalCase_ == 1;
      }
      /**
       * <code>.server.Order order = 1;</code>
       */
      public server.ProtoReqRecv.Order getOrder() {
        if (orderBuilder_ == null) {
          if (generalCase_ == 1) {
            return (server.ProtoReqRecv.Order) general_;
          }
          return server.ProtoReqRecv.Order.getDefaultInstance();
        } else {
          if (generalCase_ == 1) {
            return orderBuilder_.getMessage();
          }
          return server.ProtoReqRecv.Order.getDefaultInstance();
        }
      }
      /**
       * <code>.server.Order order = 1;</code>
       */
      public Builder setOrder(server.ProtoReqRecv.Order value) {
        if (orderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          general_ = value;
          onChanged();
        } else {
          orderBuilder_.setMessage(value);
        }
        generalCase_ = 1;
        return this;
      }
      /**
       * <code>.server.Order order = 1;</code>
       */
      public Builder setOrder(
          server.ProtoReqRecv.Order.Builder builderForValue) {
        if (orderBuilder_ == null) {
          general_ = builderForValue.build();
          onChanged();
        } else {
          orderBuilder_.setMessage(builderForValue.build());
        }
        generalCase_ = 1;
        return this;
      }
      /**
       * <code>.server.Order order = 1;</code>
       */
      public Builder mergeOrder(server.ProtoReqRecv.Order value) {
        if (orderBuilder_ == null) {
          if (generalCase_ == 1 &&
              general_ != server.ProtoReqRecv.Order.getDefaultInstance()) {
            general_ = server.ProtoReqRecv.Order.newBuilder((server.ProtoReqRecv.Order) general_)
                .mergeFrom(value).buildPartial();
          } else {
            general_ = value;
          }
          onChanged();
        } else {
          if (generalCase_ == 1) {
            orderBuilder_.mergeFrom(value);
          }
          orderBuilder_.setMessage(value);
        }
        generalCase_ = 1;
        return this;
      }
      /**
       * <code>.server.Order order = 1;</code>
       */
      public Builder clearOrder() {
        if (orderBuilder_ == null) {
          if (generalCase_ == 1) {
            generalCase_ = 0;
            general_ = null;
            onChanged();
          }
        } else {
          if (generalCase_ == 1) {
            generalCase_ = 0;
            general_ = null;
          }
          orderBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.server.Order order = 1;</code>
       */
      public server.ProtoReqRecv.Order.Builder getOrderBuilder() {
        return getOrderFieldBuilder().getBuilder();
      }
      /**
       * <code>.server.Order order = 1;</code>
       */
      public server.ProtoReqRecv.OrderOrBuilder getOrderOrBuilder() {
        if ((generalCase_ == 1) && (orderBuilder_ != null)) {
          return orderBuilder_.getMessageOrBuilder();
        } else {
          if (generalCase_ == 1) {
            return (server.ProtoReqRecv.Order) general_;
          }
          return server.ProtoReqRecv.Order.getDefaultInstance();
        }
      }
      /**
       * <code>.server.Order order = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          server.ProtoReqRecv.Order, server.ProtoReqRecv.Order.Builder, server.ProtoReqRecv.OrderOrBuilder> 
          getOrderFieldBuilder() {
        if (orderBuilder_ == null) {
          if (!(generalCase_ == 1)) {
            general_ = server.ProtoReqRecv.Order.getDefaultInstance();
          }
          orderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              server.ProtoReqRecv.Order, server.ProtoReqRecv.Order.Builder, server.ProtoReqRecv.OrderOrBuilder>(
                  (server.ProtoReqRecv.Order) general_,
                  getParentForChildren(),
                  isClean());
          general_ = null;
        }
        generalCase_ = 1;
        onChanged();;
        return orderBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:server.General)
    }

    // @@protoc_insertion_point(class_scope:server.General)
    private static final server.ProtoReqRecv.General DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new server.ProtoReqRecv.General();
    }

    public static server.ProtoReqRecv.General getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<General>
        PARSER = new com.google.protobuf.AbstractParser<General>() {
      public General parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new General(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<General> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<General> getParserForType() {
      return PARSER;
    }

    public server.ProtoReqRecv.General getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_Order_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_Order_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_General_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_General_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033protobuf/protoReqRecv.proto\022\006server\"A\n" +
      "\005Order\022\017\n\007company\030\001 \001(\t\022\020\n\010quantity\030\002 \001(" +
      "\005\022\025\n\rprice_min_max\030\003 \001(\005\"4\n\007General\022\036\n\005o" +
      "rder\030\001 \001(\0132\r.server.OrderH\000B\t\n\007generalb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_server_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_Order_descriptor,
        new java.lang.String[] { "Company", "Quantity", "PriceMinMax", });
    internal_static_server_General_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_server_General_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_General_descriptor,
        new java.lang.String[] { "Order", "General", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
