%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.1

-ifndef(protoReqRecvErlang).
-define(protoReqRecvErlang, true).

-define(protoReqRecvErlang_gpb_version, "4.1.1").

-ifndef('ORDER_PB_H').
-define('ORDER_PB_H', true).
-record('Order',
        {company = []           :: iolist() | undefined, % = 1
         quantity = 0           :: integer() | undefined, % = 2, 32 bits
         price_min_max = 0      :: integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('GENERAL_PB_H').
-define('GENERAL_PB_H', true).
-record('General',
        {general                :: {order, #'Order'{}} | undefined % oneof
        }).
-endif.

-endif.
