%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.1

-ifndef(protoAuthErlang).
-define(protoAuthErlang, true).

-define(protoAuthErlang_gpb_version, "4.1.1").

-ifndef('AUTH_PB_H').
-define('AUTH_PB_H', true).
-record('Auth',
        {name = []              :: iolist() | undefined, % = 1
         password = []          :: iolist() | undefined, % = 2
         register = []          :: iolist() | undefined % = 3
        }).
-endif.

-ifndef('RESPONSEAUTH_PB_H').
-define('RESPONSEAUTH_PB_H', true).
-record('ResponseAuth',
        {statusResponse = []    :: iolist() | undefined % = 1
        }).
-endif.

-endif.
