%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.1

-ifndef(protoReqRecvErlang).
-define(protoReqRecvErlang, true).

-define(protoReqRecvErlang_gpb_version, "4.1.1").

-ifndef('SELL_PB_H').
-define('SELL_PB_H', true).
-record('Sell',
        {companySell = []       :: iolist() | undefined, % = 1
         qttSell = 0            :: integer() | undefined, % = 2, 32 bits
         priceMin = 0.0         :: float() | integer() | infinity | '-infinity' | nan | undefined % = 3
        }).
-endif.

-ifndef('BUY_PB_H').
-define('BUY_PB_H', true).
-record('Buy',
        {companyBuy = []        :: iolist() | undefined, % = 1
         qttBuy = 0             :: integer() | undefined, % = 2, 32 bits
         priceMax = 0.0         :: float() | integer() | infinity | '-infinity' | nan | undefined % = 3
        }).
-endif.

-ifndef('GENERAL_PB_H').
-define('GENERAL_PB_H', true).
-record('General',
        {general                :: {buy, #'Buy'{}} | {sell, #'Sell'{}} | undefined % oneof
        }).
-endif.

-endif.
